# Generated by Django 5.0.4 on 2024-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_loginlogoutlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('budget', models.IntegerField()),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ad_images/')),
            ],
        ),
    ]
