# Generated by Django 5.0.4 on 2024-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='company',
            field=models.CharField(default='Linx', max_length=50),
        ),
    ]
