# Generated by Django 5.0.4 on 2024-05-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ad_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
