# Generated by Django 5.0.4 on 2024-05-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userprofile_is_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='person',
        ),
    ]
