# Generated by Django 5.0.4 on 2024-05-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_author_comment_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='metadata',
            field=models.TextField(blank=True),
        ),
    ]
